[package]
name = "acm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
async-openai = "0.18.0"
dirs = "5.0.1"
inquire = "0.6.2"
regex = "1.10.2"
reqwest = "0.11.23"
serde = { version = "1.0.195", features = ["derive"] }
spinoff = "0.8.0"
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
which = "5.0.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
